INKSCAPE?=inkscape
OPTIPNG?=optipng -o7 --strip all --quiet
SCSS?=sassc

DEFAULT_THEME_COLOR?=\#2777ff
COLOR_VARIANTS ?= Blue Black Grey Green Violet Red White Teal Cyan Orange Magenta Yellow Brown

UNWANTED_VARIANTS ?= White-Light Black-Dark

COLOR_Black?=\#000000
TEXT_COLOR_Black?=\#ffffff

COLOR_Blue?=\#2777ff
TEXT_COLOR_Blue?=\#ffffff

COLOR_Brown?=\#c37837
TEXT_COLOR_Brown?=\#ffffff

COLOR_Cyan?=\#0ccfd9
TEXT_COLOR_Cyan?=\#000000

COLOR_Green?=\#06a284
TEXT_COLOR_Green?=\#ffffff

COLOR_Grey?=\#737680
TEXT_COLOR_Grey?=\#ffffff

COLOR_Magenta?=\#cd0245
TEXT_COLOR_Magenta?=\#ffffff

COLOR_Orange?=\#fd7d00
TEXT_COLOR_Orange?=\#ffffff

COLOR_Red?=\#ec0101
TEXT_COLOR_Red?=\#ffffff

COLOR_Teal?=\#0099a1
TEXT_COLOR_Teal?=\#ffffff

COLOR_Violet?=\#962ac3
TEXT_COLOR_Violet?=\#ffffff

COLOR_White?=\#ffffff
TEXT_COLOR_White?=\#000000

COLOR_Yellow?=\#ffd86e
TEXT_COLOR_Yellow?=\#000000

